export const SET_WEIKA_INVID = 'SET_WEIKA_INVID'

export const SAVE_RECEIVER_ADDRESS = 'SAVE_RECEIVER_ADDRESS'

export const SAVE_BEING_EDITOR_ADDRESS = 'SAVE_BEING_EDITOR_ADDRESS'

export const CLEAR_STATE = 'CLEAR_STATE'

export const CHOICE_DETAILS = 'CHOICE_DETAILS'

export const EXCHANHE = 'EXCHANHE'

export const COMMENTS = 'COMMENTS'

export const SET_USER_INFO = 'SET_USER_INFO'

export const UPDATE_LOADING = 'UPDATE_LOADING'
